import { VouchPost, VouchOrder, Influencer } from '@/types/vouch';
import { calculatePostCPM, formatCPM } from '@/lib/cpmUtils';
import { format } from 'date-fns';

const formatNumber = (num: number | null | undefined): string => {
  if (num === null || num === undefined) return 'N/A';
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`;
  return num.toString();
};

const formatCurrency = (amount: number, currency = 'USD'): string => {
  return new Intl.NumberFormat('en-US', { 
    style: 'currency', 
    currency,
    maximumFractionDigits: 0 
  }).format(amount);
};

// Caption generation logic (same as in PostDetailDialog)
const generateCaption = (post: VouchPost): string => {
  const captions: Record<string, string> = {
    'inf-2': "Faith + mindset + style 🙏 @styleco_official really understood the assignment with this one. Quality is unmatched! #ad #styleco #fashion #mindset",
    'inf-3': "Vancouver fits check ✈️🇨🇦 @styleco_official coming through with the heat! These pieces are perfect for content days. Link in bio! #gifted #styleco #contentcreator",
  };
  
  return captions[post.influencer_id] || "Loving my new pieces from @styleco_official! 💕 The quality is incredible and I can't stop wearing them. Check out my stories for more details! #styleco #fashion #sponsored";
};

// Download helper
function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportPostToMarkdown(
  post: VouchPost, 
  order: VouchOrder | undefined,
  allPosts: VouchPost[],
  allOrders: VouchOrder[]
) {
  const platform = post.platform.charAt(0).toUpperCase() + post.platform.slice(1);
  const handle = post.platform === 'instagram' 
    ? `@${post.influencer?.instagram_username}` 
    : `@${post.influencer?.tiktok_username}`;
  const followers = post.platform === 'instagram' 
    ? post.influencer?.instagram_followers 
    : post.influencer?.tiktok_followers;
  const engagementRate = post.platform === 'instagram' 
    ? post.influencer?.instagram_engagement_rate 
    : post.influencer?.tiktok_engagement_rate;

  const cpm = calculatePostCPM(post, order);
  const caption = generateCaption(post);

  let md = `# Post Performance Report

> Generated: ${format(new Date(), 'MMMM d, yyyy h:mm a')}
> This report is formatted for LLM consumption.

---

## Influencer Information

| Field | Value |
|-------|-------|
| Name | ${post.influencer?.full_name || 'Unknown'} |
| Platform | ${platform} |
| Handle | ${handle} |
| Followers | ${formatNumber(followers)} |
| Engagement Rate | ${engagementRate?.toFixed(1) || '—'}% |
| Email | ${post.influencer?.email || 'N/A'} |
| Category | ${post.influencer?.category || 'N/A'} |

---

## Post Details

| Field | Value |
|-------|-------|
| Platform | ${platform} |
| Detected At | ${format(new Date(post.detected_at), 'MMMM d, yyyy h:mm a')} |
| Post URL | ${post.post_url} |

### Caption

\`\`\`
${caption}
\`\`\`

---

## Performance Metrics

| Metric | Value |
|--------|-------|
| Views | ${formatNumber(post.views)} |
| Likes | ${formatNumber(post.likes)} |
| Comments | ${formatNumber(post.comments)} |
| Engagement Rate | ${post.engagement_rate?.toFixed(2) || '—'}% |
| CPM (Cost Per Mille) | ${cpm !== null ? formatCPM(cpm) : 'N/A'} |

> CPM Formula: ((COGS + tax + shipping) ÷ views) × 1,000

`;

  if (order) {
    md += `---

## Order Details

| Field | Value |
|-------|-------|
| Retail Value | ${formatCurrency(order.order_total || 0)} |
| COGS | ${formatCurrency(order.cogs || 0)} |
| Tax | ${formatCurrency(order.sales_tax || 0)} |
| Shipping | ${formatCurrency(order.shipping_cost || 0)} |
| Status | ${order.status.replace(/_/g, ' ').toUpperCase()} |
| Items | ${order.items_count || 1} |
| Created | ${format(new Date(order.created_at), 'MMM d, yyyy')} |
${order.shopify_order_id ? `| Shopify Order | #${order.shopify_order_id} |` : ''}

`;
  }

  md += `---

*Generated by Vouch · vouch.io*
`;

  const filename = `vouch-post-${post.influencer?.full_name?.replace(/\s+/g, '-').toLowerCase() || 'unknown'}-${format(new Date(post.detected_at), 'yyyy-MM-dd')}.md`;
  downloadMarkdown(md, filename);
}

// Audience data type (same as pdfExport)
interface AudienceData {
  location: { country: string; percentage: number }[];
  cities: { city: string; percentage: number }[];
  languages: { language: string; percentage: number }[];
  age: { range: string; percentage: number }[];
  gender: { type: string; percentage: number }[];
  interests: string[];
}

const mockAudienceData: Record<string, AudienceData> = {
  'inf-1': {
    location: [
      { country: 'United States', percentage: 45 },
      { country: 'United Kingdom', percentage: 18 },
      { country: 'Canada', percentage: 12 },
      { country: 'Australia', percentage: 8 },
      { country: 'Other', percentage: 17 },
    ],
    cities: [
      { city: 'Los Angeles', percentage: 18 },
      { city: 'New York', percentage: 15 },
      { city: 'London', percentage: 12 },
      { city: 'Toronto', percentage: 8 },
      { city: 'Miami', percentage: 6 },
    ],
    languages: [
      { language: 'English', percentage: 78 },
      { language: 'Spanish', percentage: 12 },
      { language: 'French', percentage: 6 },
      { language: 'Other', percentage: 4 },
    ],
    age: [
      { range: '18-24', percentage: 50 },
      { range: '25-34', percentage: 37 },
      { range: '35-44', percentage: 13 },
    ],
    gender: [
      { type: 'Female', percentage: 68 },
      { type: 'Male', percentage: 32 },
    ],
    interests: ['Fashion', 'Beauty', 'Lifestyle', 'Travel'],
  },
  'inf-2': {
    location: [
      { country: 'United States', percentage: 62 },
      { country: 'Germany', percentage: 10 },
      { country: 'Japan', percentage: 8 },
      { country: 'South Korea', percentage: 6 },
      { country: 'Other', percentage: 14 },
    ],
    cities: [
      { city: 'San Francisco', percentage: 22 },
      { city: 'Seattle', percentage: 14 },
      { city: 'Austin', percentage: 10 },
      { city: 'Tokyo', percentage: 8 },
      { city: 'Berlin', percentage: 6 },
    ],
    languages: [
      { language: 'English', percentage: 72 },
      { language: 'Japanese', percentage: 10 },
      { language: 'German', percentage: 8 },
      { language: 'Korean', percentage: 6 },
      { language: 'Other', percentage: 4 },
    ],
    age: [
      { range: '18-24', percentage: 55 },
      { range: '25-34', percentage: 35 },
      { range: '35-44', percentage: 10 },
    ],
    gender: [
      { type: 'Male', percentage: 75 },
      { type: 'Female', percentage: 25 },
    ],
    interests: ['Tech', 'Gaming', 'Gadgets', 'Reviews'],
  },
  'inf-3': {
    location: [
      { country: 'United States', percentage: 55 },
      { country: 'United Kingdom', percentage: 15 },
      { country: 'Australia', percentage: 10 },
      { country: 'Canada', percentage: 8 },
      { country: 'Other', percentage: 12 },
    ],
    cities: [
      { city: 'Los Angeles', percentage: 20 },
      { city: 'Sydney', percentage: 12 },
      { city: 'London', percentage: 10 },
      { city: 'Denver', percentage: 8 },
      { city: 'Vancouver', percentage: 6 },
    ],
    languages: [
      { language: 'English', percentage: 88 },
      { language: 'Spanish', percentage: 7 },
      { language: 'Other', percentage: 5 },
    ],
    age: [
      { range: '18-24', percentage: 50 },
      { range: '25-34', percentage: 40 },
      { range: '35-44', percentage: 10 },
    ],
    gender: [
      { type: 'Female', percentage: 60 },
      { type: 'Male', percentage: 40 },
    ],
    interests: ['Fitness', 'Wellness', 'Nutrition', 'Yoga'],
  },
};

const defaultAudienceData: AudienceData = {
  location: [
    { country: 'United States', percentage: 50 },
    { country: 'United Kingdom', percentage: 15 },
    { country: 'Canada', percentage: 10 },
    { country: 'Other', percentage: 25 },
  ],
  cities: [
    { city: 'New York', percentage: 18 },
    { city: 'Los Angeles', percentage: 14 },
    { city: 'London', percentage: 10 },
    { city: 'Chicago', percentage: 8 },
    { city: 'Toronto', percentage: 6 },
  ],
  languages: [
    { language: 'English', percentage: 82 },
    { language: 'Spanish', percentage: 10 },
    { language: 'Other', percentage: 8 },
  ],
  age: [
    { range: '18-24', percentage: 50 },
    { range: '25-34', percentage: 35 },
    { range: '35-44', percentage: 15 },
  ],
  gender: [
    { type: 'Female', percentage: 55 },
    { type: 'Male', percentage: 45 },
  ],
  interests: ['Lifestyle', 'Fashion', 'Entertainment'],
};

export function exportInfluencerToMarkdown(
  influencer: Influencer,
  orders: VouchOrder[] = [],
  allPosts: VouchPost[] = [],
  allOrders: VouchOrder[] = [],
  brandId?: string
) {
  const influencerPosts = allPosts.filter(p => p.influencer_id === influencer.id);
  const influencerOrders = allOrders.filter(o => o.influencer_id === influencer.id);
  
  // Brand-specific metrics
  const brandOrders = brandId ? influencerOrders.filter(o => o.brand_id === brandId) : influencerOrders;
  const brandVerifiedOrders = brandOrders.filter(o => o.status === 'post_verified');
  const brandVerifiedPosts = influencerPosts.filter(p => {
    if (brandId && p.brand_id !== brandId) return false;
    const order = influencerOrders.find(o => o.id === p.order_id);
    return order?.status === 'post_verified';
  });
  
  const totalRetailValue = brandOrders.reduce((sum, o) => sum + o.order_total, 0);
  const totalCOGS = brandOrders.reduce((sum, o) => sum + (o.cogs || 0), 0);
  const totalViews = brandVerifiedPosts.reduce((sum, p) => sum + (p.views || 0), 0);
  const totalLikes = brandVerifiedPosts.reduce((sum, p) => sum + (p.likes || 0), 0);

  const audienceData = mockAudienceData[influencer.id] || defaultAudienceData;

  let md = `# Influencer Profile Report

> Generated: ${format(new Date(), 'MMMM d, yyyy h:mm a')}
> This report is formatted for LLM consumption.

---

## Basic Information

| Field | Value |
|-------|-------|
| Name | ${influencer.full_name || 'Unknown'} |
| Email | ${influencer.email} |
| Phone | ${influencer.phone || 'N/A'} |
| Category | ${influencer.category || 'N/A'} |
| Bio | ${influencer.bio || 'N/A'} |

---

## Social Media Presence

### Instagram
| Field | Value |
|-------|-------|
| Username | @${influencer.instagram_username || 'N/A'} |
| Followers | ${formatNumber(influencer.instagram_followers)} |
| Engagement Rate | ${influencer.instagram_engagement_rate?.toFixed(1) || 'N/A'}% |

### TikTok
| Field | Value |
|-------|-------|
| Username | @${influencer.tiktok_username || 'N/A'} |
| Followers | ${formatNumber(influencer.tiktok_followers)} |
| Engagement Rate | ${influencer.tiktok_engagement_rate?.toFixed(1) || 'N/A'}% |

---

## Brand Performance Metrics

| Metric | Value |
|--------|-------|
| Total Orders | ${brandOrders.length} |
| Verified Posts | ${brandVerifiedPosts.length} |
| Total Retail Value | ${formatCurrency(totalRetailValue)} |
| Total COGS | ${formatCurrency(totalCOGS)} |
| Total Views | ${formatNumber(totalViews)} |
| Total Likes | ${formatNumber(totalLikes)} |

---

## Order History

`;

  if (brandOrders.length > 0) {
    md += `| Date | Status | Retail Value | Items |
|------|--------|--------------|-------|
`;
    brandOrders.slice(0, 10).forEach(order => {
      md += `| ${format(new Date(order.created_at), 'MMM d, yyyy')} | ${order.status.replace(/_/g, ' ')} | ${formatCurrency(order.order_total)} | ${order.items_count || 1} |
`;
    });
  } else {
    md += `No orders found.
`;
  }

  md += `
---

## Audience Insights

### Geographic Distribution (Countries)
| Country | Percentage |
|---------|------------|
`;
  audienceData.location.forEach(loc => {
    md += `| ${loc.country} | ${loc.percentage}% |
`;
  });

  md += `
### Top Cities
| City | Percentage |
|------|------------|
`;
  audienceData.cities.forEach(city => {
    md += `| ${city.city} | ${city.percentage}% |
`;
  });

  md += `
### Languages
| Language | Percentage |
|----------|------------|
`;
  audienceData.languages.forEach(lang => {
    md += `| ${lang.language} | ${lang.percentage}% |
`;
  });

  md += `
### Age Distribution
| Age Range | Percentage |
|-----------|------------|
`;
  audienceData.age.forEach(age => {
    md += `| ${age.range} | ${age.percentage}% |
`;
  });

  md += `
### Gender Distribution
| Gender | Percentage |
|--------|------------|
`;
  audienceData.gender.forEach(g => {
    md += `| ${g.type} | ${g.percentage}% |
`;
  });

  md += `
### Interests
${audienceData.interests.map(i => `- ${i}`).join('\n')}

---

*Generated by Vouch · vouch.io*
`;

  const filename = `vouch-influencer-${influencer.full_name?.replace(/\s+/g, '-').toLowerCase() || 'unknown'}-${format(new Date(), 'yyyy-MM-dd')}.md`;
  downloadMarkdown(md, filename);
}

// Re-export type from pdfExport for consistency
import type { AnalyticsReportData } from './pdfExport';
export type { AnalyticsReportData };

export function exportAnalyticsToMarkdown(data: AnalyticsReportData) {
  let md = `# Analytics Report

> Timeframe: ${data.timeframe}
> Date Range: ${format(data.dateRange.from, 'MMM d, yyyy')} - ${format(data.dateRange.to, 'MMM d, yyyy')}
> Generated: ${format(new Date(), 'MMMM d, yyyy h:mm a')}
> This report is formatted for LLM consumption.

---

## Gift Metrics Summary

| Metric | Value |
|--------|-------|
| Total Gifts | ${data.totalGifts} |
| Total Items | ${data.totalItems} |
| Retail Value | ${formatCurrency(data.retailValue)} |
| COGS | ${formatCurrency(data.cogs)} |
| Actualized Spend | ${formatCurrency(data.actualizedSpend)} |
| Charged Amount | ${formatCurrency(data.charged)} |
| Avg Retail Value | ${formatCurrency(data.avgRetailValue)} |
| Avg COGS | ${formatCurrency(data.avgCogs)} |

---

## Post Performance

| Metric | Value |
|--------|-------|
| Total Posts | ${data.totalPosts} |
| Post Rate | ${data.postRate.toFixed(1)}% |
| Total Views | ${formatNumber(data.totalViews)} |
| Total Likes | ${formatNumber(data.totalLikes)} |
| Total Comments | ${formatNumber(data.totalComments)} |
| Avg Engagement Rate | ${data.avgEngagement.toFixed(2)}% |
| Avg CPM | ${formatCurrency(data.avgCpm)} |

---

## Influencer Metrics

| Metric | Value |
|--------|-------|
| Unique Creators | ${data.uniqueCreators} |
| Total Followers | ${formatNumber(data.totalFollowers)} |
| Avg Followers | ${formatNumber(data.avgFollowers)} |
| Avg Engagement Rate | ${data.avgEngagementRate.toFixed(2)}% |
| Instagram Creators | ${data.instagramCreators} |
| TikTok Creators | ${data.tiktokCreators} |

---

## Order Status Distribution

| Status | Count |
|--------|-------|
`;
  data.statusData.forEach(s => {
    md += `| ${s.name} | ${s.value} |
`;
  });

  md += `
---

## Top Performing Influencers

| Rank | Name | Platform | Category | Views |
|------|------|----------|----------|-------|
`;
  data.topInfluencers.forEach((inf, i) => {
    md += `| ${i + 1} | ${inf.name} | ${inf.platform} | ${inf.category} | ${formatNumber(inf.views)} |
`;
  });

  md += `
---

## Top Products

| Rank | Product | Order Count | Total Value |
|------|---------|-------------|-------------|
`;
  data.topProducts.forEach((p, i) => {
    md += `| ${i + 1} | ${p.name} | ${p.count} | ${formatCurrency(p.value)} |
`;
  });

  md += `
---

## Audience Insights

### Geographic Distribution (Countries)
| Country | Percentage |
|---------|------------|
`;
  data.audienceInsights.countries.forEach(c => {
    md += `| ${c.country} | ${c.percentage}% |
`;
  });

  md += `
### Top Cities
| City | Percentage |
|------|------------|
`;
  data.audienceInsights.cities.forEach(c => {
    md += `| ${c.city} | ${c.percentage}% |
`;
  });

  md += `
### Languages
| Language | Percentage |
|----------|------------|
`;
  data.audienceInsights.languages.forEach(l => {
    md += `| ${l.language} | ${l.percentage}% |
`;
  });

  md += `
### Age Distribution
| Age Range | Percentage |
|-----------|------------|
`;
  data.audienceInsights.ageRanges.forEach(a => {
    md += `| ${a.range} | ${a.percentage}% |
`;
  });

  md += `
### Gender Distribution
| Gender | Percentage |
|--------|------------|
`;
  data.audienceInsights.gender.forEach(g => {
    md += `| ${g.type} | ${g.percentage}% |
`;
  });

  md += `
### Interests
${data.audienceInsights.interests.map(i => `- ${i}`).join('\n')}

---

*Generated by Vouch · vouch.io*
`;

  const filename = `vouch-analytics-${format(new Date(), 'yyyy-MM-dd')}.md`;
  downloadMarkdown(md, filename);
}
